### ISSUE TITLE
BSOD while running mhddos

### ISSUE THREAD

**Issue by ghost** [porthole-ascend-cinnamon/mhddos_proxy_releases#15]
While running mhddos for like 10 mins, the Windows crashes (BSOD) randomly with an error code IRQL_NOT_LESS_OR_EQUAL. I tried both Win10 and Win11, both were installed cleanly just to run this tool. I tried lowering threads and connections but still crashing. Do you know any reasons?

```
091322-28734-01.dmp	13-09-2022 17:39:51	IRQL_NOT_LESS_OR_EQUAL	0x0000000a	00000000`00000000
00000000`000000ff	00000000`00000000	fffff807`20bfa635	ntoskrnl.exe	ntoskrnl.exe+3f88c0	NT Kernel & System	Microsoft® Windows® Operating System	Microsoft Corporation	10.0.19041.1889 (WinBuild.160101.0800)	x64
ntoskrnl.exe+3f88c0					C:\Windows\Minidump\091322-28734-01.dmp	4	15	19041	1.043.668	
13-09-2022 17:43:01	
```

**Comment by porthole-ascend-cinnamon** [comment]
Hi! We are not aware of these issue

**Comment by porthole-ascend-cinnamon** [comment]
Hello!
You are the first one to report these issue. We are testing each release on all platforms.
Are you running the latest v63? There was an issue with Windows on v62, although a different one, leading to program crash.
Quick google search suggests this may be caused by antivirus. We are testing with Windows Defender enabled, but maybe try disabling it.
Another possibility is a faulty hardware and some specific feature we use are triggering the BSOD, however I don't know what code path may be triggered only after 10 minutes.

**Comment by porthole-ascend-cinnamon** [comment]
Hmm, there is a self-update loop running each 10 minutes. Try using `'--no-updates` and see whether it still crashes

**Comment by porthole-ascend-cinnamon** [comment]
Oh well, you have an unusual setup, cannot guarantee it's gonna work. Try Linux VM or Docker if that's an option

**Comment by porthole-ascend-cinnamon** [comment]
Nah, you definitely shouldn't)
