### ISSUE TITLE
Please add releases for Android

### ISSUE THREAD

**Issue by Andrii-Asiox** [porthole-ascend-cinnamon/mhddos_proxy_releases#7]

**Comment by porthole-ascend-cinnamon** [comment]
I am afraid there is technical difficulties which cannot be overcome now. 
Aarch64 binaries are supposed to work on Termux, but apparently they aren't. 
The only next step is building (somehow?) an .apk, but the required time investment cannot be justified (at least for now) due to small user base and low output of android devices.

**Comment by Andrii-Asiox** [comment]
😥 ok. So I will continue to use db100n and distress on my android devices
